### ISSUE TITLE
Kit fontawesome: forbiden access

### ISSUE THREAD

**Issue by LECARROU** [app-generator/app-generator#224]
Django material kit use font awesome kit to display font awesome icons.
Since last days, font awesome icons are not displayed in my projects in production.
When inspecting static files, seems https://kit.fontawesome.com/42d5adcbca.js (base.html and base_background.html) is not loaded with 403 error (forbidden).

Thanks for help

**Comment by app-generator** [comment]
Hello @LECARROU 

We have the fix for this, but is not deployed in all products. 

Here is the fix for [Django Soft PRO](https://appseed.us/product/soft-ui-dashboard-pro/django/) that uses the same resource:

https://django-soft-dash-pro.onrender.com/static/assets/js/plugins/fontawesome.min.js

We will add this hot fix to all related products. 

![image](https://github.com/user-attachments/assets/9050f461-4d50-4104-9e1d-8df5c3e085f5)

**Comment by LECARROU** [comment]
Hi, 
thanks for replying.
problem is that I used the "kit.fontawesome" in many of my projects in production.
that means I will have to stop all my projects to deploy the fix with upoladed js file mentionned ahead
that will be a huge works and will impact thousand of users in trials...
would it be possible to authorized access to previous kit.fontawesome?

**Comment by app-generator** [comment]
Hello @LECARROU 

Sorry, we don't have access or control over the `fontawesome.com` domain or subdomains. 
The one and only solution remains to update the path in the source code. 

If helps, we can assist with this effort (needs a budget, and can't be done in support).  

Ping us back regarding this matter. 

TY!
